name: Java SpringBoot CI

on:
  push:
    branches: [feature/* , develop ]
  workflow_dispatch:
    inputs:
      maven_opts:
        description: 'Options for Maven. Example: "-Xmx512m"'
        required: true
        default: '-Xmx512m'

      sonar_project_key:
        description: 'SonarQube project key'
        required: true

      sonar_project_name:
        description: 'SonarQube project name'
        required: true

      sonar_host_url:
        description: 'SonarQube host URL'
        required: true

      sonar_login_token:
        description: 'SonarQube login token'
        required: true

      sonar_sources:
        description: 'SonarQube sources'
        required: true

      sonar_exclusions:
        description: 'SonarQube exclusions'
        required: true

      npm_install:
        description: 'Run npm install'
        required: true
        default: 'true'

      npm_test:
        description: 'Run npm test'
        required: true
        default: 'false'

jobs:
  build:
    runs-on: self-hosted
    env:
      MAVEN_OPTS: ${{ github.event.inputs.maven_opts }}
      SONAR_PROJECT_KEY: ${{ github.event.inputs.sonar_project_key }}
      SONAR_PROJECT_NAME: ${{ github.event.inputs.sonar_project_name }}
      SONAR_HOST_URL: ${{ github.event.inputs.sonar_host_url }}
      SONAR_LOGIN_TOKEN: ${{ github.event.inputs.sonar_login_token }}
      SONAR_SOURCES: ${{ github.event.inputs.sonar_sources }}
      SONAR_EXCLUSIONS: ${{ github.event.inputs.sonar_exclusions }}
      NPM_INSTALL: ${{ github.event.inputs.npm_install }}
      NPM_TEST: ${{ github.event.inputs.npm_test }}
      # Agregar otras variables de entorno como se necesiten

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0

      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
        
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.7.0
        with:
          java-version: 11
          maven-version: 3.8.7

      - name: Install & Compile with Maven
        run: mvn clean install -DskipTests
        working-directory: backend/form-service

      - name: Download dependencies with NPM
        run: |
          if [ "${{ env.NPM_INSTALL }}" == "true" ]; then
            npm ci
          fi
        working-directory: front

      - name: Test CI with NPM
        run: |
          if [ "${{ env.NPM_TEST }}" == "true" ]; then
            npm run test-ci
          fi
        working-directory: front

      - name: Run Sonar Scanner
        run: |
          mvn install verify sonar:sonar \
            -Dsonar.projectKey=${{ env.SONAR_PROJECT_KEY }} \
            -Dsonar.projectName=${{ env.SONAR_PROJECT_NAME }} \
            -Dsonar.host.url=${{ env.SONAR_HOST_URL }} \
            -Dsonar.login=${{ env.SONAR_LOGIN_TOKEN }} \
            -Dsonar.sources=${{ env.SONAR_SOURCES }} \
            -Dsonar.exclusions=${{ env.SONAR_EXCLUSIONS }}
        working-directory: generator/jdk11/office-service

