name: Compile TITAN
on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
      project_name: 
        required: true
        type: string
      sonar_server: 
        required: true
        type: string
      sonar_token: 
        required: true
        type: string
jobs:
  Compile-TITAN-Solution:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0

      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - name: Download dependencies with NPM
        run: npm ci
        working-directory: front
        if: success()

      - name: Test CI with NPM
        run: npm run test-ci 
        working-directory: front
        if: success()

      - name: sonar-scanner
        run: |
          /opt/sonar-scanner/bin/sonar-scanner \
          -Dsonar.projectKey=${{inputs.project_name}} \
          -Dsonar.host.url=${{inputs.sonar_server}} \
          -Dsonar.login=${{inputs.sonar_token}} \
          -Dsonar.sourceEncoding=UTF-8 \
          -Dsonar.sources=src/app \
          -Dsonar.exclusions=**/node_modules/**,**/*.spec.ts,**/*.module.ts,**/app.child.imports.ts \
          -Dsonar.tests=src \
          -Dsonar.test.inclusions=**/*.spec.ts \
          -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info
        working-directory: front
        shell: bash
        if: success()

      
  
    
