name: Compile TITAN
on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
      projectKey: 
        required: true
        type: string
        
jobs:
  Compile-TITAN-Solution:
    runs-on: ubuntu-latest
    steps: 
      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        with: 
          projectBaseDir: front
          args: >
           -Dsonar.projectKey=${{ inputs.projectKey }}
           -Dsonar.sourceEncoding=UTF-8 
           -Dsonar.sources=src/app 
           -Dsonar.exclusions=**/node_modules/**,**/*.spec.ts,**/*.module.ts,**/app.child.imports.ts 
           -Dsonar.tests=src 
           -Dsonar.test.inclusions=**/*.spec.ts 
           -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      


          
    
          


      

      
  
    
