name: Compile TITAN
on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
jobs:
  Compile-TITAN-Solution:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - name: Download dependencies with NPM
        run: npm ci
        working-directory: front
        if: success()

      - name: Test CI with NPM
        run: npm run test-ci 
        working-directory: front
        if: success()



      

      
  
    
