name: Compile ALNILAM
on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
      projectKey: 
        required: true
        type: string

jobs:
  Compile-ALNILAM-Solution:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v3
      with: 
        fetch-depth: 0
