name: Compile TITAN
on:
  workflow_call:
    inputs:
      node-version:
          required: true
          type: string
jobs:
  
  Setup-Node:
    uses: JaredDevAxity/AR_26_A_ARCHERNAR_ACTIONS/.github/workflows/setupNode.yml@main
    with: 
      node-version: ${{ inputs.node-version }}

  Download-Dependencies:
    uses: JaredDevAxity/AR_26_A_ARCHERNAR_ACTIONS/.github/workflows/downloadDependenciesNPM.yml@main

    
