name: Compile TITAN
on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
      projectKey: 
        required: true
        type: string
        
jobs:
  Compile-TITAN-Solution:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout
      uses: actions/checkout@v3
      with: 
        fetch-depth: 0

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}

  

      


          
    
          


      

      
  
    
