name: Compile TITAN
on:
  workflow_call:
    inputs:
      node-version:
          required: true
          type: string
jobs:
  
  Compile-Titan-Solution:
    uses: JaredDevAxity/AR_26_A_ARCHERNAR_ACTIONS/.github/workflows/setupNode.yml@main
    with: 
      node-version: ${{ inputs.node-version }}
