name: Download dependencies with NPM
on:
  workflow_call:
    
jobs:
  Solution:
      runs-on: ubuntu-latest
      steps: 
      - name: Checkout 
        uses: actions/checkout@v3
        with:
          fetch-depht: 0
      - name: NPM
        run: npm ci
        working-directory: front
        
