name: Reusable Java SpringBoot CI
on: 
  workflow_call:
    inputs: 
      node-version: 
        required: true
        type: string
      java-version: 
        required: true
        type: string
      java-distribution: 
        required: true
        type: string
      maven-version: 
        required: true
        type: string

jobs: 
  Compile-Java-solution: 
    runs-on: ubuntu-latest

    steps: 
      - name: Config git
        run: git config --system core.longpaths true

      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depht: 0

      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - name: Update npm
        run: npm install -g npm@latest

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.java-version }}
          distribution: ${{ inputs.java-distribution }}

      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.7.0
        with:
          java-version: ${{inputs.java-version }}
          maven-version: ${{inputs.maven-version }}

      - name: Install Yeoman
        run: | 
          npm install -g yo generator-code yeoman-generator
          npm install
          npm link 
        working-directory: generator/jdk11

      - name: Generate code
        run: yo jdk11-springboot
        working-directory: generator/jdk11

  #    - name: Install & Compile with maven
  #      run: mvn clean install -DskipTests
  #      working-directory: generator/jdk11/office-service

   #   - name: Run sonar 
   #     run: mvn install verify sonar:sonar -Dsonar.projectKey=23_Orion_ALNILAM -Dsonar.projectName=23_Orion_ALNILAM -Dsonar.host.url=https://devtools.axity.com/sonarlts -Dsonar.login=6ed1e516ca77f7afe02d184789e8032f3d424478 -Dsonar.sonar.sources=target/**/*,src/java/**/* -Dsonar.scm.exclusions.disabled=true -Dsonar.exclusions=src/java/test/**,src/main/java/com/axity/office/commons/**/*.java,src/main/java/com/axity/office/Application.java,src/main/java/com/axity/office/handler/ValidationExceptionHandler.java,src/main/java/com/axity/office/service/util/MessageSerializer.java,*/**Dto.java,*/**DO.java \
   #     working-directory: generator/jdk11/office-service

      
      

      
