name: Java SpringBoot CI
run-name: Reusable workflow Java
on:
  workflow_call:   
    inputs: 
      node-version: 
        required: true
        type: string

jobs:
  Compile-Java-Solution:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with: 
          fetch-depht: 0

      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
        
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.7.0
        with:
          java-version: 11
          maven-version: 3.8.7

      - name: Install & Compile with maven
        run: mvn clean install -DskipTests
        working-directory: backend/form-service

      - name: Download dependencies with NPM
        run: npm ci
        working-directory: front
