name: Workflow MIMTAKA CI

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
      run-path:
        required: true
        type: string

jobs:
  Build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node ${{inputs.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - name: Install Yeoman
        run: |
          npm install -g yo generator-code yeoman-generator
          npm install
          npm link
        working-directory: ${{inputs.run-path}}/generator/6.0/Generator/generator-netcore6

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.x"
          include-prerelease: true

      - name: Generate code
        run: yo netcore6
        working-directory: ${{inputs.run-path}}/generator/6.0/Generator/generator-netcore6

      - name: Archive Generated Code
        uses: actions/upload-artifact@v4
        with:
          name: generated-code-net
          path: ${{inputs.run-path}}/generator/6.0/Generator/generator-netcore6/arquetipounittesting-service

  Test:
    needs: Build
    runs-on: windows-latest
    steps:
      - name: Download Generated Code
        uses: actions/download-artifact@v4
        with:
          name: generated-code-net

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "6.x"
          include-prerelease: true

      - name: Restore dependencies
        run: dotnet restore
        # working-directory: generator/6.0/Generator/generator-netcore6/arquetipounittesting-service

      - name: Build
        run: dotnet build --no-restore
      #   working-directory: generator/6.0/Generator/generator-netcore6/arquetipounittesting-service

      - name: Test
        run: dotnet test --no-build --verbosity normal
      #   working-directory: generator/6.0/Generator/generator-netcore6/arquetipounittesting-service

      - uses: actions/setup-java@v1
        with:
          java-version: "17"

      - name: SonarQube Analysis
        run: |
          dotnet tool install --global dotnet-sonarscanner
          dotnet sonarscanner begin /k:"${{secrets.SONAR_PROJECT_KEY}}" /d:sonar.login="${{secrets.SONAR_TOKEN}}" /d:sonar.host.url="${{secrets.SONAR_HOST_URL}}"
          dotnet build --configuration Release
          dotnet test --configuration .\Axity.ArquetipoUnitTesting.Api\Axity.ArquetipoUnitTesting.sln /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput=\"TestResults/\"
          dotnet sonarscanner end /d:sonar.login="${{secrets.SONAR_TOKEN}}"
      #   working-directory: generator/6.0/Generator/generator-netcore6/arquetipounittesting-service
