name: Setup Node
on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
jobs:
  Compile-Node-Solution:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout 
        uses: actions/checkout@v3
        with:
          fetch-depht: 0
      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
