name: Compile ALNILAM
on:
  workflow_call:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depht: 0

      - name: Setup
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
        
      - name: Setup Maven Action
        uses: s4u/setup-maven-action@v1.7.0
        with:
          java-version: 11
          maven-version: 3.8.7

      - name: Install Yeoman
        run: | 
          npm install -g yo generator-code yeoman-generator
          npm install
          npm link 
        working-directory: generator/jdk11

      - name: Generate code
        run: yo jdk11-springboot
        working-directory: generator/jdk11

      - name: Install & Compile with maven
        run: mvn clean install -DskipTests
        working-directory: generator/jdk11/office-service

      - name: Run sonar 
        run: mvn install verify sonar:sonar -Dsonar.projectKey=Test_CREA_Sonar_Archernar -Dsonar.projectName=ALNILAM-Test -Dsonar.host.url=https://devtools.axity.com/sonarlts -Dsonar.login=sqp_62d48b60880f8f08933ee1c5fcaacb584c2f361e -Dsonar.sonar.sources=target/**/*,src/java/**/* -Dsonar.scm.exclusions.disabled=true -Dsonar.exclusions=src/java/test/**,src/main/java/com/axity/office/commons/**/*.java,src/main/java/com/axity/office/Application.java,src/main/java/com/axity/office/handler/ValidationExceptionHandler.java,src/main/java/com/axity/office/service/util/MessageSerializer.java,*/**Dto.java,*/**DO.java \
        working-directory: generator/jdk11/office-service
