name: Reuzable workflow TITAN Angular CI

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
      run-path:
        required: true
        type: string

jobs:
  Build-Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node ${{ inputs.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - name: Download dependencies with NPM
        run: npm ci
        working-directory: ${{ inputs.run-path }}/front

      - name: Build
        run: npm run build
        working-directory: front

      - name: Empaquetar
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

      - name: test CI with NPM
        run: npm run test-ci
        working-directory: ${{ inputs.run-path }}/front

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        with:
          projectBaseDir: front
          args: >
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.sourceEncoding=UTF-8
            -Dsonar.sources=src/app
            -Dsonar.exclusions=**/node_modules/**,**/*.spec.ts,**/*.module.ts,**/app.child.imports.ts
            -Dsonar.tests=src
            -Dsonar.test.inclusions=**/*.spec.ts
            -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    #   - name: sonar-scanner
    #     run: |
    #       /opt/sonar-scanner/bin/sonar-scanner \
    #       -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
    #       -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
    #       -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
    #       -Dsonar.sourceEncoding=UTF-8 \
    #       -Dsonar.sources=src/app \
    #       -Dsonar.exclusions=**/node_modules/**,**/*.spec.ts,**/*.module.ts,**/app.child.imports.ts \
    #       -Dsonar.tests=src \
    #       -Dsonar.test.inclusions=**/*.spec.ts \
    #       -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info
    #     working-directory: ${{ inputs.run-path}}/front
    #     shell: bash
