name: Reuzable workflow TITAN Angular CI

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string
      run-path:
        required: true
        type: string

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node ${{ inputs.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}

      - name: Download dependencies with NPM
        run: npm ci
        working-directory: ${{ inputs.run-path }}/front

      - name: test CI with NPM
        run: npm run test-ci
        working-directory: ${{ inputs.run-path }}/front

      - name: sonar-scanner
        run: |
          /opt/sonar-scanner/bin/sonar-scanner \
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
          -Dsonar.sourceEncoding=UTF-8 \
          -Dsonar.sources=src/app \
          -Dsonar.exclusions=**/node_modules/**,**/*.spec.ts,**/*.module.ts,**/app.child.imports.ts \
          -Dsonar.tests=src \
          -Dsonar.test.inclusions=**/*.spec.ts \
          -Dsonar.typescript.lcov.reportPaths=coverage/lcov.info
        working-directory: ${{ inputs.run-path}}/front
        shell: bash
